version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
